///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ATP_TopCV
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ATP_TopCVRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("74fd19c5-ce83-4d38-acf1-09f47b5f1384")]
    public partial class ATP_TopCVRepository : RepoGenBaseFolder
    {
        static ATP_TopCVRepository instance = new ATP_TopCVRepository();
        ATP_TopCVRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder _đăngkytaikhoảnnhatuyểndụnggoogl;
        ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder _đăngkytaikhoảnnhatuyểndụng;

        /// <summary>
        /// Gets the singleton class instance representing the ATP_TopCVRepository element repository.
        /// </summary>
        [RepositoryFolder("74fd19c5-ce83-4d38-acf1-09f47b5f1384")]
        public static ATP_TopCVRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ATP_TopCVRepository() 
            : base("ATP_TopCVRepository", "/", null, 0, false, "74fd19c5-ce83-4d38-acf1-09f47b5f1384", ".\\RepositoryImages\\ATP_TopCVRepository74fd19c5.rximgres")
        {
            _applicationundertest = new ATP_TopCVRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _đăngkytaikhoảnnhatuyểndụnggoogl = new ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder(this);
            _đăngkytaikhoảnnhatuyểndụng = new ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("74fd19c5-ce83-4d38-acf1-09f47b5f1384")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("cce7b1b0-2c7c-4938-8056-7fc99d02680b")]
        public virtual ATP_TopCVRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The ĐăngKyTaiKhoảnNhaTuyểnDụngGoogl folder.
        /// </summary>
        [RepositoryFolder("8b73d748-488c-420e-a292-4530fef3ae3d")]
        public virtual ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder ĐăngKyTaiKhoảnNhaTuyểnDụngGoogl
        {
            get { return _đăngkytaikhoảnnhatuyểndụnggoogl; }
        }

        /// <summary>
        /// The ĐăngKyTaiKhoảnNhaTuyểnDụng folder.
        /// </summary>
        [RepositoryFolder("877487b5-3798-4654-8f8b-4321564991cc")]
        public virtual ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder ĐăngKyTaiKhoảnNhaTuyểnDụng
        {
            get { return _đăngkytaikhoảnnhatuyểndụng; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ATP_TopCVRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("cce7b1b0-2c7c-4938-8056-7fc99d02680b")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "cce7b1b0-2c7c-4938-8056-7fc99d02680b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cce7b1b0-2c7c-4938-8056-7fc99d02680b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cce7b1b0-2c7c-4938-8056-7fc99d02680b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder folder.
        /// </summary>
        [RepositoryFolder("8b73d748-488c-420e-a292-4530fef3ae3d")]
        public partial class ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _đăngkytaikhoảnnhatuyểndụngInfo;

            /// <summary>
            /// Creates a new ĐăngKyTaiKhoảnNhaTuyểnDụngGoogl  folder.
            /// </summary>
            public ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ĐăngKyTaiKhoảnNhaTuyểnDụngGoogl", "/form[@title~'^Đăng\\ ký\\ Tài\\ khoản\\ Nhà\\ tuy']", parentFolder, 30000, null, true, "8b73d748-488c-420e-a292-4530fef3ae3d", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename~'^Đăng\\ ký\\ Tài\\ khoản\\ Nhà\\ tuy']/container/container[1]", 30000, null, "6ca48d20-7be8-4d79-9872-153927147b04");
                _closeInfo = new RepoItemInfo(this, "Close", "container[@accessiblename~'^Đăng\\ ký\\ Tài\\ khoản\\ Nhà\\ tuy']//container[@accessiblename='Infobar Container']/?/?/button[@accessiblename='Close']", 30000, null, "6918fcdf-7ae1-462c-b90d-583da9d00466");
                _đăngkytaikhoảnnhatuyểndụngInfo = new RepoItemInfo(this, "ĐăngKyTaiKhoảnNhaTuyểnDụng", "container[@accessiblename~'^Đăng\\ ký\\ Tài\\ khoản\\ Nhà\\ tuy']/container[@accessiblename='Google Chrome']//tabpage[@accessiblename~'^Đăng\\ ký\\ Tài\\ khoản\\ Nhà\\ tuy']", 30000, null, "09cf1728-00fb-4422-854a-c6f542c2bdb5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8b73d748-488c-420e-a292-4530fef3ae3d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8b73d748-488c-420e-a292-4530fef3ae3d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("6ca48d20-7be8-4d79-9872-153927147b04")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("6ca48d20-7be8-4d79-9872-153927147b04")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("6918fcdf-7ae1-462c-b90d-583da9d00466")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("6918fcdf-7ae1-462c-b90d-583da9d00466")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The ĐăngKyTaiKhoảnNhaTuyểnDụng item.
            /// </summary>
            [RepositoryItem("09cf1728-00fb-4422-854a-c6f542c2bdb5")]
            public virtual Ranorex.TabPage ĐăngKyTaiKhoảnNhaTuyểnDụng
            {
                get
                {
                    return _đăngkytaikhoảnnhatuyểndụngInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ĐăngKyTaiKhoảnNhaTuyểnDụng item info.
            /// </summary>
            [RepositoryItemInfo("09cf1728-00fb-4422-854a-c6f542c2bdb5")]
            public virtual RepoItemInfo ĐăngKyTaiKhoảnNhaTuyểnDụngInfo
            {
                get
                {
                    return _đăngkytaikhoảnnhatuyểndụngInfo;
                }
            }
        }

        /// <summary>
        /// The ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder folder.
        /// </summary>
        [RepositoryFolder("877487b5-3798-4654-8f8b-4321564991cc")]
        public partial class ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _hoantấtInfo;
            RepoItemInfo _đonglạiInfo;
            PasswordInfoClass _passwordInfo;
            RepoItemInfo _emailInfo;
            PasswordConfirmationInfoClass _passwordconfirmationInfo;
            RepoItemInfo _đonglại1Info;
            RepoItemInfo _đacolỗixảyraInfo;
            RepoItemInfo _modalbodyInfo;
            ModalErrorMessageInfoClass _modalerrormessageInfo;

            /// <summary>
            /// Creates a new ĐăngKyTaiKhoảnNhaTuyểnDụng  folder.
            /// </summary>
            public ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ĐăngKyTaiKhoảnNhaTuyểnDụng", "/dom[@domain='tuyendung.topcv.vn']", parentFolder, 30000, null, false, "877487b5-3798-4654-8f8b-4321564991cc", "")
            {
                _hoantấtInfo = new RepoItemInfo(this, "HoanTất", ".//div[#'personal-info']//a[@innertext='Hoàn tất']", 30000, null, "a2df2c05-3c26-4638-8dac-0946fb041b06");
                _đonglạiInfo = new RepoItemInfo(this, "ĐongLại", ".//div[#'modal-error']/div/div/div[2]/button[@innertext='Đóng lại']", 30000, null, "380835dc-4d72-4161-ac49-4dec28bbe8e6");
                _passwordInfo = new PasswordInfoClass(this);
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "b14d95ce-b80a-4f5f-8d21-6802d3cd4cfc");
                _passwordconfirmationInfo = new PasswordConfirmationInfoClass(this);
                _đonglại1Info = new RepoItemInfo(this, "ĐongLại1", ".//div[#'modal-success']/div/div/div[2]/button[@innertext='Đóng lại']", 30000, null, "358715e9-c77f-4eeb-9f30-9cedb5ea4719");
                _đacolỗixảyraInfo = new RepoItemInfo(this, "ĐaCoLỗiXảyRa", ".//div[#'modal-error']/div/div/div[1]/p[@innertext='Đã có lỗi xảy ra']", 30000, null, "6dce7232-bf3e-440a-9b4f-d91c52b59da3");
                _modalbodyInfo = new RepoItemInfo(this, "ModalBody", ".//div[#'modal-error']/div/div/div[1]", 30000, null, "3ae46367-0b84-4e78-98b8-212f309da6ce");
                _modalerrormessageInfo = new ModalErrorMessageInfoClass(this);
            }

            /// <summary>
            /// The PasswordInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("158eeb44-16c6-49d9-b7c0-f66e7c757f9b")]
            public class PasswordInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PasswordInfoClass class constructor.
                /// </summary>
                public PasswordInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Password", ".//input[#'password']", 30000, null, "158eeb44-16c6-49d9-b7c0-f66e7c757f9b")
                { }

                /// <summary>
                /// Gets the Ma_hoa_password1 item image.
                /// </summary>
                /// <returns>The Ma_hoa_password1 image.</returns>
                [RepositoryImage("03d8436d-2bc2-41b5-972a-01038f1d578f")]
                public CompressedImage GetMa_hoa_password1()
                {
                    return GetImage("03d8436d-2bc2-41b5-972a-01038f1d578f");
                }

                /// <summary>
                /// Gets the Ma_hoa_password1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("03d8436d-2bc2-41b5-972a-01038f1d578f")]
                public CompressedImage GetMa_hoa_password1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("03d8436d-2bc2-41b5-972a-01038f1d578f", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("d2e1d5b0-4bc5-4607-85c4-e18fd533eade")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("d2e1d5b0-4bc5-4607-85c4-e18fd533eade");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d2e1d5b0-4bc5-4607-85c4-e18fd533eade")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d2e1d5b0-4bc5-4607-85c4-e18fd533eade", cropRect);
                }
            }

            /// <summary>
            /// The PasswordConfirmationInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("349b6bb7-b3d2-41c4-bd43-d786302862aa")]
            public class PasswordConfirmationInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PasswordConfirmationInfoClass class constructor.
                /// </summary>
                public PasswordConfirmationInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "PasswordConfirmation", ".//input[#'password_confirmation']", 30000, null, "349b6bb7-b3d2-41c4-bd43-d786302862aa")
                { }

                /// <summary>
                /// Gets the Ma_hoa_confirm_password1 item image.
                /// </summary>
                /// <returns>The Ma_hoa_confirm_password1 image.</returns>
                [RepositoryImage("91911e09-d911-48f4-92a4-21ea0c6a311a")]
                public CompressedImage GetMa_hoa_confirm_password1()
                {
                    return GetImage("91911e09-d911-48f4-92a4-21ea0c6a311a");
                }

                /// <summary>
                /// Gets the Ma_hoa_confirm_password1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("91911e09-d911-48f4-92a4-21ea0c6a311a")]
                public CompressedImage GetMa_hoa_confirm_password1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("91911e09-d911-48f4-92a4-21ea0c6a311a", cropRect);
                }

                /// <summary>
                /// Gets the Ma_hoa_password1 item image.
                /// </summary>
                /// <returns>The Ma_hoa_password1 image.</returns>
                [RepositoryImage("86de77a3-b19e-434c-930d-f9fbd97bb014")]
                public CompressedImage GetMa_hoa_password1()
                {
                    return GetImage("86de77a3-b19e-434c-930d-f9fbd97bb014");
                }

                /// <summary>
                /// Gets the Ma_hoa_password1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("86de77a3-b19e-434c-930d-f9fbd97bb014")]
                public CompressedImage GetMa_hoa_password1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("86de77a3-b19e-434c-930d-f9fbd97bb014", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("0908f107-966e-4aa5-81b1-4d8a95992540")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("0908f107-966e-4aa5-81b1-4d8a95992540");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("0908f107-966e-4aa5-81b1-4d8a95992540")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("0908f107-966e-4aa5-81b1-4d8a95992540", cropRect);
                }
            }

            /// <summary>
            /// The ModalErrorMessageInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("366451d2-50b3-4e9c-9ede-f9d27dc1ef24")]
            public class ModalErrorMessageInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ModalErrorMessageInfoClass class constructor.
                /// </summary>
                public ModalErrorMessageInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ModalErrorMessage", ".//p[#'modal-error-message']", 30000, null, "366451d2-50b3-4e9c-9ede-f9d27dc1ef24")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("ae5c64bc-84e1-401e-b96b-5d8dd17bfbcc")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("ae5c64bc-84e1-401e-b96b-5d8dd17bfbcc");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("ae5c64bc-84e1-401e-b96b-5d8dd17bfbcc")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("ae5c64bc-84e1-401e-b96b-5d8dd17bfbcc", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("877487b5-3798-4654-8f8b-4321564991cc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("877487b5-3798-4654-8f8b-4321564991cc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HoanTất item.
            /// </summary>
            [RepositoryItem("a2df2c05-3c26-4638-8dac-0946fb041b06")]
            public virtual Ranorex.ATag HoanTất
            {
                get
                {
                    return _hoantấtInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HoanTất item info.
            /// </summary>
            [RepositoryItemInfo("a2df2c05-3c26-4638-8dac-0946fb041b06")]
            public virtual RepoItemInfo HoanTấtInfo
            {
                get
                {
                    return _hoantấtInfo;
                }
            }

            /// <summary>
            /// The ĐongLại item.
            /// </summary>
            [RepositoryItem("380835dc-4d72-4161-ac49-4dec28bbe8e6")]
            public virtual Ranorex.ButtonTag ĐongLại
            {
                get
                {
                    return _đonglạiInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ĐongLại item info.
            /// </summary>
            [RepositoryItemInfo("380835dc-4d72-4161-ac49-4dec28bbe8e6")]
            public virtual RepoItemInfo ĐongLạiInfo
            {
                get
                {
                    return _đonglạiInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("158eeb44-16c6-49d9-b7c0-f66e7c757f9b")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("158eeb44-16c6-49d9-b7c0-f66e7c757f9b")]
            public virtual PasswordInfoClass PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("b14d95ce-b80a-4f5f-8d21-6802d3cd4cfc")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("b14d95ce-b80a-4f5f-8d21-6802d3cd4cfc")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The PasswordConfirmation item.
            /// </summary>
            [RepositoryItem("349b6bb7-b3d2-41c4-bd43-d786302862aa")]
            public virtual Ranorex.InputTag PasswordConfirmation
            {
                get
                {
                    return _passwordconfirmationInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PasswordConfirmation item info.
            /// </summary>
            [RepositoryItemInfo("349b6bb7-b3d2-41c4-bd43-d786302862aa")]
            public virtual PasswordConfirmationInfoClass PasswordConfirmationInfo
            {
                get
                {
                    return _passwordconfirmationInfo;
                }
            }

            /// <summary>
            /// The ĐongLại1 item.
            /// </summary>
            [RepositoryItem("358715e9-c77f-4eeb-9f30-9cedb5ea4719")]
            public virtual Ranorex.ButtonTag ĐongLại1
            {
                get
                {
                    return _đonglại1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ĐongLại1 item info.
            /// </summary>
            [RepositoryItemInfo("358715e9-c77f-4eeb-9f30-9cedb5ea4719")]
            public virtual RepoItemInfo ĐongLại1Info
            {
                get
                {
                    return _đonglại1Info;
                }
            }

            /// <summary>
            /// The ĐaCoLỗiXảyRa item.
            /// </summary>
            [RepositoryItem("6dce7232-bf3e-440a-9b4f-d91c52b59da3")]
            public virtual Ranorex.PTag ĐaCoLỗiXảyRa
            {
                get
                {
                    return _đacolỗixảyraInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ĐaCoLỗiXảyRa item info.
            /// </summary>
            [RepositoryItemInfo("6dce7232-bf3e-440a-9b4f-d91c52b59da3")]
            public virtual RepoItemInfo ĐaCoLỗiXảyRaInfo
            {
                get
                {
                    return _đacolỗixảyraInfo;
                }
            }

            /// <summary>
            /// The ModalBody item.
            /// </summary>
            [RepositoryItem("3ae46367-0b84-4e78-98b8-212f309da6ce")]
            public virtual Ranorex.DivTag ModalBody
            {
                get
                {
                    return _modalbodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ModalBody item info.
            /// </summary>
            [RepositoryItemInfo("3ae46367-0b84-4e78-98b8-212f309da6ce")]
            public virtual RepoItemInfo ModalBodyInfo
            {
                get
                {
                    return _modalbodyInfo;
                }
            }

            /// <summary>
            /// The ModalErrorMessage item.
            /// </summary>
            [RepositoryItem("366451d2-50b3-4e9c-9ede-f9d27dc1ef24")]
            public virtual Ranorex.PTag ModalErrorMessage
            {
                get
                {
                    return _modalerrormessageInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ModalErrorMessage item info.
            /// </summary>
            [RepositoryItemInfo("366451d2-50b3-4e9c-9ede-f9d27dc1ef24")]
            public virtual ModalErrorMessageInfoClass ModalErrorMessageInfo
            {
                get
                {
                    return _modalerrormessageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
