///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ATP_TopCV
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ATP_TopCVRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("74fd19c5-ce83-4d38-acf1-09f47b5f1384")]
    public partial class ATP_TopCVRepository : RepoGenBaseFolder
    {
        static ATP_TopCVRepository instance = new ATP_TopCVRepository();
        ATP_TopCVRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder _đăngkytaikhoảnnhatuyểndụnggoogl;
        ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder _đăngkytaikhoảnnhatuyểndụng;
        ATP_TopCVRepositoryFolders.SavePasswordAppFolder _savepassword;
        ATP_TopCVRepositoryFolders.DropdownAppFolder _dropdown;

        /// <summary>
        /// Gets the singleton class instance representing the ATP_TopCVRepository element repository.
        /// </summary>
        [RepositoryFolder("74fd19c5-ce83-4d38-acf1-09f47b5f1384")]
        public static ATP_TopCVRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ATP_TopCVRepository() 
            : base("ATP_TopCVRepository", "/", null, 0, false, "74fd19c5-ce83-4d38-acf1-09f47b5f1384", ".\\RepositoryImages\\ATP_TopCVRepository74fd19c5.rximgres")
        {
            _applicationundertest = new ATP_TopCVRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _đăngkytaikhoảnnhatuyểndụnggoogl = new ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder(this);
            _đăngkytaikhoảnnhatuyểndụng = new ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder(this);
            _savepassword = new ATP_TopCVRepositoryFolders.SavePasswordAppFolder(this);
            _dropdown = new ATP_TopCVRepositoryFolders.DropdownAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("74fd19c5-ce83-4d38-acf1-09f47b5f1384")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("cce7b1b0-2c7c-4938-8056-7fc99d02680b")]
        public virtual ATP_TopCVRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The ĐăngKyTaiKhoảnNhaTuyểnDụngGoogl folder.
        /// </summary>
        [RepositoryFolder("8b73d748-488c-420e-a292-4530fef3ae3d")]
        public virtual ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder ĐăngKyTaiKhoảnNhaTuyểnDụngGoogl
        {
            get { return _đăngkytaikhoảnnhatuyểndụnggoogl; }
        }

        /// <summary>
        /// The ĐăngKyTaiKhoảnNhaTuyểnDụng folder.
        /// </summary>
        [RepositoryFolder("877487b5-3798-4654-8f8b-4321564991cc")]
        public virtual ATP_TopCVRepositoryFolders.ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder ĐăngKyTaiKhoảnNhaTuyểnDụng
        {
            get { return _đăngkytaikhoảnnhatuyểndụng; }
        }

        /// <summary>
        /// The SavePassword folder.
        /// </summary>
        [RepositoryFolder("efecb01f-bac5-4b91-9197-6e9479053fc2")]
        public virtual ATP_TopCVRepositoryFolders.SavePasswordAppFolder SavePassword
        {
            get { return _savepassword; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("3693d967-bd3a-49ff-b378-91e2289a9c90")]
        public virtual ATP_TopCVRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ATP_TopCVRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("cce7b1b0-2c7c-4938-8056-7fc99d02680b")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "cce7b1b0-2c7c-4938-8056-7fc99d02680b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cce7b1b0-2c7c-4938-8056-7fc99d02680b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cce7b1b0-2c7c-4938-8056-7fc99d02680b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder folder.
        /// </summary>
        [RepositoryFolder("8b73d748-488c-420e-a292-4530fef3ae3d")]
        public partial class ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _đăngkytaikhoảnnhatuyểndụngInfo;

            /// <summary>
            /// Creates a new ĐăngKyTaiKhoảnNhaTuyểnDụngGoogl  folder.
            /// </summary>
            public ĐăngKyTaiKhoảnNhaTuyểnDụngGooglAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ĐăngKyTaiKhoảnNhaTuyểnDụngGoogl", "/form[@title~'^Đăng\\ ký\\ Tài\\ khoản\\ Nhà\\ tuy']", parentFolder, 30000, null, true, "8b73d748-488c-420e-a292-4530fef3ae3d", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename~'^Đăng\\ ký\\ Tài\\ khoản\\ Nhà\\ tuy']/container/container[1]", 30000, null, "6ca48d20-7be8-4d79-9872-153927147b04");
                _closeInfo = new RepoItemInfo(this, "Close", "container[@accessiblename~'^Đăng\\ ký\\ Tài\\ khoản\\ Nhà\\ tuy']//container[@accessiblename='Infobar Container']/?/?/button[@accessiblename='Close']", 30000, null, "6918fcdf-7ae1-462c-b90d-583da9d00466");
                _đăngkytaikhoảnnhatuyểndụngInfo = new RepoItemInfo(this, "ĐăngKyTaiKhoảnNhaTuyểnDụng", "container[@accessiblename~'^Đăng\\ ký\\ Tài\\ khoản\\ Nhà\\ tuy']/container[@accessiblename='Google Chrome']//tabpage[@accessiblename~'^Đăng\\ ký\\ Tài\\ khoản\\ Nhà\\ tuy']", 30000, null, "09cf1728-00fb-4422-854a-c6f542c2bdb5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8b73d748-488c-420e-a292-4530fef3ae3d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8b73d748-488c-420e-a292-4530fef3ae3d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("6ca48d20-7be8-4d79-9872-153927147b04")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("6ca48d20-7be8-4d79-9872-153927147b04")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("6918fcdf-7ae1-462c-b90d-583da9d00466")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("6918fcdf-7ae1-462c-b90d-583da9d00466")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The ĐăngKyTaiKhoảnNhaTuyểnDụng item.
            /// </summary>
            [RepositoryItem("09cf1728-00fb-4422-854a-c6f542c2bdb5")]
            public virtual Ranorex.TabPage ĐăngKyTaiKhoảnNhaTuyểnDụng
            {
                get
                {
                    return _đăngkytaikhoảnnhatuyểndụngInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ĐăngKyTaiKhoảnNhaTuyểnDụng item info.
            /// </summary>
            [RepositoryItemInfo("09cf1728-00fb-4422-854a-c6f542c2bdb5")]
            public virtual RepoItemInfo ĐăngKyTaiKhoảnNhaTuyểnDụngInfo
            {
                get
                {
                    return _đăngkytaikhoảnnhatuyểndụngInfo;
                }
            }
        }

        /// <summary>
        /// The ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder folder.
        /// </summary>
        [RepositoryFolder("877487b5-3798-4654-8f8b-4321564991cc")]
        public partial class ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder : RepoGenBaseFolder
        {
            ATP_TopCVRepositoryFolders.ColMd9Folder _colmd9;
            ATP_TopCVRepositoryFolders.Select2GenderResultsFolder _select2genderresults;
            ATP_TopCVRepositoryFolders.DivTagRowFolder _divtagrow;
            RepoItemInfo _hoantấtInfo;
            RepoItemInfo _đonglạiInfo;
            PasswordInfoClass _passwordInfo;
            RepoItemInfo _emailInfo;
            PasswordConfirmationInfoClass _passwordconfirmationInfo;
            RepoItemInfo _đonglại1Info;
            RepoItemInfo _đacolỗixảyraInfo;
            ModalBodyInfoClass _modalbodyInfo;
            ModalErrorMessageInfoClass _modalerrormessageInfo;
            RepoItemInfo _fullnameInfo;
            ModalContentInfoClass _modalcontentInfo;
            RepoItemInfo _phoneInfo;
            RepoItemInfo _tempcompanynameInfo;
            RepoItemInfo _somebtagInfo;
            RepoItemInfo _select2selectionarrowInfo;
            RepoItemInfo _agreetermInfo;
            RepoItemInfo _taikhoảnInfo;
            RepoItemInfo _thoatInfo;
            RepoItemInfo _chucmừnganhchịđađăngkithanhcongInfo;
            RepoItemInfo _skypeInfo;
            RepoItemInfo _searchInfo;
            RepoItemInfo _navbarInfo;
            RepoItemInfo _trangchủInfo;
            RepoItemInfo _select2positioncontainerInfo;
            RepoItemInfo _atagtaikhoảnInfo;

            /// <summary>
            /// Creates a new ĐăngKyTaiKhoảnNhaTuyểnDụng  folder.
            /// </summary>
            public ĐăngKyTaiKhoảnNhaTuyểnDụngAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ĐăngKyTaiKhoảnNhaTuyểnDụng", "/dom[@domain='tuyendung.topcv.vn']", parentFolder, 30000, null, false, "877487b5-3798-4654-8f8b-4321564991cc", "")
            {
                _colmd9 = new ATP_TopCVRepositoryFolders.ColMd9Folder(this);
                _select2genderresults = new ATP_TopCVRepositoryFolders.Select2GenderResultsFolder(this);
                _divtagrow = new ATP_TopCVRepositoryFolders.DivTagRowFolder(this);
                _hoantấtInfo = new RepoItemInfo(this, "HoanTất", ".//div[#'personal-info']//a[@innertext='Hoàn tất']", 30000, null, "a2df2c05-3c26-4638-8dac-0946fb041b06");
                _đonglạiInfo = new RepoItemInfo(this, "ĐongLại", ".//div[#'modal-error']/div/div/div[2]/button[@innertext='Đóng lại']", 30000, null, "380835dc-4d72-4161-ac49-4dec28bbe8e6");
                _passwordInfo = new PasswordInfoClass(this);
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "b14d95ce-b80a-4f5f-8d21-6802d3cd4cfc");
                _passwordconfirmationInfo = new PasswordConfirmationInfoClass(this);
                _đonglại1Info = new RepoItemInfo(this, "ĐongLại1", ".//div[#'modal-success']/div/div/div[2]/button[@innertext='Đóng lại']", 30000, null, "358715e9-c77f-4eeb-9f30-9cedb5ea4719");
                _đacolỗixảyraInfo = new RepoItemInfo(this, "ĐaCoLỗiXảyRa", ".//div[#'modal-error']/div/div/div[1]/p[@innertext='Đã có lỗi xảy ra']", 30000, null, "6dce7232-bf3e-440a-9b4f-d91c52b59da3");
                _modalbodyInfo = new ModalBodyInfoClass(this);
                _modalerrormessageInfo = new ModalErrorMessageInfoClass(this);
                _fullnameInfo = new RepoItemInfo(this, "Fullname", ".//input[#'fullname']", 30000, null, "5f4c2c9e-82c2-4a64-9c51-71af32f45ac5");
                _modalcontentInfo = new ModalContentInfoClass(this);
                _phoneInfo = new RepoItemInfo(this, "Phone", ".//input[#'phone']", 30000, null, "21ddb8a6-eb66-4ef0-9999-63f8b1114fd1");
                _tempcompanynameInfo = new RepoItemInfo(this, "TempCompanyName", ".//input[#'temp_company_name']", 30000, null, "fee9dacd-4f86-4211-b872-c85784c45163");
                _somebtagInfo = new RepoItemInfo(this, "SomeBTag", ".//div[#'personal-info']/div[2]/div/div[9]/div//b", 30000, null, "1574c626-922b-4275-80dc-61c1edacdee8");
                _select2selectionarrowInfo = new RepoItemInfo(this, "Select2SelectionArrow", ".//div[#'personal-info']/div[2]/div/div[9]/div/span/span[1]/span/span[2]", 30000, null, "efadaf0f-4eea-4a19-b2c6-47ffb3417057");
                _agreetermInfo = new RepoItemInfo(this, "AgreeTerm", ".//input[#'agree_term']", 30000, null, "95f8e1dc-104d-4c4a-890b-f6880d8cd56f");
                _taikhoảnInfo = new RepoItemInfo(this, "TaiKhoản", ".//div[#'navbar']//a[@innertext='Tài khoản ']", 30000, null, "3bc15f56-06f0-44b7-99d4-f278740f1dcc");
                _thoatInfo = new RepoItemInfo(this, "Thoat", ".//div[#'navbar']/ul/li[7]/ul/?/?/a[@innertext='Thoát']", 30000, null, "312f386b-2021-4064-bddc-4fab7b4d0e7e");
                _chucmừnganhchịđađăngkithanhcongInfo = new RepoItemInfo(this, "ChucMừngAnhChịĐaĐăngKiThanhCong", "body/div[1]/div/div/div[2]/?/?/p[@innertext~'^Chúc\\ mừng\\ anh/chị\\ đã\\ đăng']", 30000, null, "34feeb44-2cec-4bd7-a54b-4d83b902661e");
                _skypeInfo = new RepoItemInfo(this, "Skype", ".//input[#'skype']", 30000, null, "aa5e61c1-bb2e-488c-aad3-f2d542475b80");
                _searchInfo = new RepoItemInfo(this, "Search", ".//div[#'personal-info']/div[2]/div/div[12]/div//ul/?/?/input[@type='search']", 30000, null, "2b331842-31da-4039-a61b-2ed5bb9df1aa");
                _navbarInfo = new RepoItemInfo(this, "Navbar", ".//div[#'navbar']", 30000, null, "0a5baa93-1bcc-40ed-afdd-e10568642d47");
                _trangchủInfo = new RepoItemInfo(this, "TrangChủ", ".//div[#'navbar']//a[@innertext='Trang chủ']", 30000, null, "308c9ffb-9fd9-4928-891e-aab654976b5d");
                _select2positioncontainerInfo = new RepoItemInfo(this, "Select2PositionContainer", ".//span[#'select2-position-container']", 30000, null, "9ca798bd-8358-4e33-b39e-37a14dc24277");
                _atagtaikhoảnInfo = new RepoItemInfo(this, "ATagTaiKhoản", ".//div[#'navbar']//a[@innertext='Tài khoản']", 30000, null, "9011d25f-8fc6-433c-9616-15158da9f8e7");
            }

            /// <summary>
            /// The PasswordInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("158eeb44-16c6-49d9-b7c0-f66e7c757f9b")]
            public class PasswordInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PasswordInfoClass class constructor.
                /// </summary>
                public PasswordInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Password", ".//input[#'password']", 30000, null, "158eeb44-16c6-49d9-b7c0-f66e7c757f9b")
                { }

                /// <summary>
                /// Gets the Ma_hoa_password1 item image.
                /// </summary>
                /// <returns>The Ma_hoa_password1 image.</returns>
                [RepositoryImage("03d8436d-2bc2-41b5-972a-01038f1d578f")]
                public CompressedImage GetMa_hoa_password1()
                {
                    return GetImage("03d8436d-2bc2-41b5-972a-01038f1d578f");
                }

                /// <summary>
                /// Gets the Ma_hoa_password1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("03d8436d-2bc2-41b5-972a-01038f1d578f")]
                public CompressedImage GetMa_hoa_password1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("03d8436d-2bc2-41b5-972a-01038f1d578f", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("d2e1d5b0-4bc5-4607-85c4-e18fd533eade")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("d2e1d5b0-4bc5-4607-85c4-e18fd533eade");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d2e1d5b0-4bc5-4607-85c4-e18fd533eade")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d2e1d5b0-4bc5-4607-85c4-e18fd533eade", cropRect);
                }
            }

            /// <summary>
            /// The PasswordConfirmationInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("349b6bb7-b3d2-41c4-bd43-d786302862aa")]
            public class PasswordConfirmationInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PasswordConfirmationInfoClass class constructor.
                /// </summary>
                public PasswordConfirmationInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "PasswordConfirmation", ".//input[#'password_confirmation']", 30000, null, "349b6bb7-b3d2-41c4-bd43-d786302862aa")
                { }

                /// <summary>
                /// Gets the Ma_hoa_confirm_password1 item image.
                /// </summary>
                /// <returns>The Ma_hoa_confirm_password1 image.</returns>
                [RepositoryImage("91911e09-d911-48f4-92a4-21ea0c6a311a")]
                public CompressedImage GetMa_hoa_confirm_password1()
                {
                    return GetImage("91911e09-d911-48f4-92a4-21ea0c6a311a");
                }

                /// <summary>
                /// Gets the Ma_hoa_confirm_password1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("91911e09-d911-48f4-92a4-21ea0c6a311a")]
                public CompressedImage GetMa_hoa_confirm_password1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("91911e09-d911-48f4-92a4-21ea0c6a311a", cropRect);
                }

                /// <summary>
                /// Gets the Ma_hoa_password1 item image.
                /// </summary>
                /// <returns>The Ma_hoa_password1 image.</returns>
                [RepositoryImage("86de77a3-b19e-434c-930d-f9fbd97bb014")]
                public CompressedImage GetMa_hoa_password1()
                {
                    return GetImage("86de77a3-b19e-434c-930d-f9fbd97bb014");
                }

                /// <summary>
                /// Gets the Ma_hoa_password1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("86de77a3-b19e-434c-930d-f9fbd97bb014")]
                public CompressedImage GetMa_hoa_password1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("86de77a3-b19e-434c-930d-f9fbd97bb014", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("0908f107-966e-4aa5-81b1-4d8a95992540")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("0908f107-966e-4aa5-81b1-4d8a95992540");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("0908f107-966e-4aa5-81b1-4d8a95992540")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("0908f107-966e-4aa5-81b1-4d8a95992540", cropRect);
                }
            }

            /// <summary>
            /// The ModalBodyInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("3ae46367-0b84-4e78-98b8-212f309da6ce")]
            public class ModalBodyInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ModalBodyInfoClass class constructor.
                /// </summary>
                public ModalBodyInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ModalBody", ".//div[#'modal-error']/div/div/div[1]", 30000, null, "3ae46367-0b84-4e78-98b8-212f309da6ce")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("500c0a7c-a684-4b09-b4c6-35ac55898218")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("500c0a7c-a684-4b09-b4c6-35ac55898218");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("500c0a7c-a684-4b09-b4c6-35ac55898218")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("500c0a7c-a684-4b09-b4c6-35ac55898218", cropRect);
                }
            }

            /// <summary>
            /// The ModalErrorMessageInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("366451d2-50b3-4e9c-9ede-f9d27dc1ef24")]
            public class ModalErrorMessageInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ModalErrorMessageInfoClass class constructor.
                /// </summary>
                public ModalErrorMessageInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ModalErrorMessage", ".//p[#'modal-error-message']", 30000, null, "366451d2-50b3-4e9c-9ede-f9d27dc1ef24")
                { }

                /// <summary>
                /// Gets the Loi_ho_ten1 item image.
                /// </summary>
                /// <returns>The Loi_ho_ten1 image.</returns>
                [RepositoryImage("d6df07ec-8768-4daa-821e-900aa49eeb2c")]
                public CompressedImage GetLoi_ho_ten1()
                {
                    return GetImage("d6df07ec-8768-4daa-821e-900aa49eeb2c");
                }

                /// <summary>
                /// Gets the Loi_ho_ten1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d6df07ec-8768-4daa-821e-900aa49eeb2c")]
                public CompressedImage GetLoi_ho_ten1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d6df07ec-8768-4daa-821e-900aa49eeb2c", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("ae5c64bc-84e1-401e-b96b-5d8dd17bfbcc")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("ae5c64bc-84e1-401e-b96b-5d8dd17bfbcc");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("ae5c64bc-84e1-401e-b96b-5d8dd17bfbcc")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("ae5c64bc-84e1-401e-b96b-5d8dd17bfbcc", cropRect);
                }
            }

            /// <summary>
            /// The ModalContentInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("3dd43007-27d6-4cd9-953c-0d118e0a1df3")]
            public class ModalContentInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ModalContentInfoClass class constructor.
                /// </summary>
                public ModalContentInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ModalContent", ".//div[#'modal-error']/div/div", 30000, null, "3dd43007-27d6-4cd9-953c-0d118e0a1df3")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("6e341117-e774-4172-95d5-1f3d0b9ebc0f")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("6e341117-e774-4172-95d5-1f3d0b9ebc0f");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("6e341117-e774-4172-95d5-1f3d0b9ebc0f")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("6e341117-e774-4172-95d5-1f3d0b9ebc0f", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("877487b5-3798-4654-8f8b-4321564991cc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("877487b5-3798-4654-8f8b-4321564991cc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HoanTất item.
            /// </summary>
            [RepositoryItem("a2df2c05-3c26-4638-8dac-0946fb041b06")]
            public virtual Ranorex.ATag HoanTất
            {
                get
                {
                    return _hoantấtInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HoanTất item info.
            /// </summary>
            [RepositoryItemInfo("a2df2c05-3c26-4638-8dac-0946fb041b06")]
            public virtual RepoItemInfo HoanTấtInfo
            {
                get
                {
                    return _hoantấtInfo;
                }
            }

            /// <summary>
            /// The ĐongLại item.
            /// </summary>
            [RepositoryItem("380835dc-4d72-4161-ac49-4dec28bbe8e6")]
            public virtual Ranorex.ButtonTag ĐongLại
            {
                get
                {
                    return _đonglạiInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ĐongLại item info.
            /// </summary>
            [RepositoryItemInfo("380835dc-4d72-4161-ac49-4dec28bbe8e6")]
            public virtual RepoItemInfo ĐongLạiInfo
            {
                get
                {
                    return _đonglạiInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("158eeb44-16c6-49d9-b7c0-f66e7c757f9b")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("158eeb44-16c6-49d9-b7c0-f66e7c757f9b")]
            public virtual PasswordInfoClass PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("b14d95ce-b80a-4f5f-8d21-6802d3cd4cfc")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("b14d95ce-b80a-4f5f-8d21-6802d3cd4cfc")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The PasswordConfirmation item.
            /// </summary>
            [RepositoryItem("349b6bb7-b3d2-41c4-bd43-d786302862aa")]
            public virtual Ranorex.InputTag PasswordConfirmation
            {
                get
                {
                    return _passwordconfirmationInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PasswordConfirmation item info.
            /// </summary>
            [RepositoryItemInfo("349b6bb7-b3d2-41c4-bd43-d786302862aa")]
            public virtual PasswordConfirmationInfoClass PasswordConfirmationInfo
            {
                get
                {
                    return _passwordconfirmationInfo;
                }
            }

            /// <summary>
            /// The ĐongLại1 item.
            /// </summary>
            [RepositoryItem("358715e9-c77f-4eeb-9f30-9cedb5ea4719")]
            public virtual Ranorex.ButtonTag ĐongLại1
            {
                get
                {
                    return _đonglại1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ĐongLại1 item info.
            /// </summary>
            [RepositoryItemInfo("358715e9-c77f-4eeb-9f30-9cedb5ea4719")]
            public virtual RepoItemInfo ĐongLại1Info
            {
                get
                {
                    return _đonglại1Info;
                }
            }

            /// <summary>
            /// The ĐaCoLỗiXảyRa item.
            /// </summary>
            [RepositoryItem("6dce7232-bf3e-440a-9b4f-d91c52b59da3")]
            public virtual Ranorex.PTag ĐaCoLỗiXảyRa
            {
                get
                {
                    return _đacolỗixảyraInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ĐaCoLỗiXảyRa item info.
            /// </summary>
            [RepositoryItemInfo("6dce7232-bf3e-440a-9b4f-d91c52b59da3")]
            public virtual RepoItemInfo ĐaCoLỗiXảyRaInfo
            {
                get
                {
                    return _đacolỗixảyraInfo;
                }
            }

            /// <summary>
            /// The ModalBody item.
            /// </summary>
            [RepositoryItem("3ae46367-0b84-4e78-98b8-212f309da6ce")]
            public virtual Ranorex.DivTag ModalBody
            {
                get
                {
                    return _modalbodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ModalBody item info.
            /// </summary>
            [RepositoryItemInfo("3ae46367-0b84-4e78-98b8-212f309da6ce")]
            public virtual ModalBodyInfoClass ModalBodyInfo
            {
                get
                {
                    return _modalbodyInfo;
                }
            }

            /// <summary>
            /// The ModalErrorMessage item.
            /// </summary>
            [RepositoryItem("366451d2-50b3-4e9c-9ede-f9d27dc1ef24")]
            public virtual Ranorex.PTag ModalErrorMessage
            {
                get
                {
                    return _modalerrormessageInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ModalErrorMessage item info.
            /// </summary>
            [RepositoryItemInfo("366451d2-50b3-4e9c-9ede-f9d27dc1ef24")]
            public virtual ModalErrorMessageInfoClass ModalErrorMessageInfo
            {
                get
                {
                    return _modalerrormessageInfo;
                }
            }

            /// <summary>
            /// The Fullname item.
            /// </summary>
            [RepositoryItem("5f4c2c9e-82c2-4a64-9c51-71af32f45ac5")]
            public virtual Ranorex.InputTag Fullname
            {
                get
                {
                    return _fullnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Fullname item info.
            /// </summary>
            [RepositoryItemInfo("5f4c2c9e-82c2-4a64-9c51-71af32f45ac5")]
            public virtual RepoItemInfo FullnameInfo
            {
                get
                {
                    return _fullnameInfo;
                }
            }

            /// <summary>
            /// The ModalContent item.
            /// </summary>
            [RepositoryItem("3dd43007-27d6-4cd9-953c-0d118e0a1df3")]
            public virtual Ranorex.DivTag ModalContent
            {
                get
                {
                    return _modalcontentInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ModalContent item info.
            /// </summary>
            [RepositoryItemInfo("3dd43007-27d6-4cd9-953c-0d118e0a1df3")]
            public virtual ModalContentInfoClass ModalContentInfo
            {
                get
                {
                    return _modalcontentInfo;
                }
            }

            /// <summary>
            /// The Phone item.
            /// </summary>
            [RepositoryItem("21ddb8a6-eb66-4ef0-9999-63f8b1114fd1")]
            public virtual Ranorex.InputTag Phone
            {
                get
                {
                    return _phoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Phone item info.
            /// </summary>
            [RepositoryItemInfo("21ddb8a6-eb66-4ef0-9999-63f8b1114fd1")]
            public virtual RepoItemInfo PhoneInfo
            {
                get
                {
                    return _phoneInfo;
                }
            }

            /// <summary>
            /// The TempCompanyName item.
            /// </summary>
            [RepositoryItem("fee9dacd-4f86-4211-b872-c85784c45163")]
            public virtual Ranorex.InputTag TempCompanyName
            {
                get
                {
                    return _tempcompanynameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TempCompanyName item info.
            /// </summary>
            [RepositoryItemInfo("fee9dacd-4f86-4211-b872-c85784c45163")]
            public virtual RepoItemInfo TempCompanyNameInfo
            {
                get
                {
                    return _tempcompanynameInfo;
                }
            }

            /// <summary>
            /// The SomeBTag item.
            /// </summary>
            [RepositoryItem("1574c626-922b-4275-80dc-61c1edacdee8")]
            public virtual Ranorex.BTag SomeBTag
            {
                get
                {
                    return _somebtagInfo.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The SomeBTag item info.
            /// </summary>
            [RepositoryItemInfo("1574c626-922b-4275-80dc-61c1edacdee8")]
            public virtual RepoItemInfo SomeBTagInfo
            {
                get
                {
                    return _somebtagInfo;
                }
            }

            /// <summary>
            /// The Select2SelectionArrow item.
            /// </summary>
            [RepositoryItem("efadaf0f-4eea-4a19-b2c6-47ffb3417057")]
            public virtual Ranorex.SpanTag Select2SelectionArrow
            {
                get
                {
                    return _select2selectionarrowInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Select2SelectionArrow item info.
            /// </summary>
            [RepositoryItemInfo("efadaf0f-4eea-4a19-b2c6-47ffb3417057")]
            public virtual RepoItemInfo Select2SelectionArrowInfo
            {
                get
                {
                    return _select2selectionarrowInfo;
                }
            }

            /// <summary>
            /// The AgreeTerm item.
            /// </summary>
            [RepositoryItem("95f8e1dc-104d-4c4a-890b-f6880d8cd56f")]
            public virtual Ranorex.InputTag AgreeTerm
            {
                get
                {
                    return _agreetermInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AgreeTerm item info.
            /// </summary>
            [RepositoryItemInfo("95f8e1dc-104d-4c4a-890b-f6880d8cd56f")]
            public virtual RepoItemInfo AgreeTermInfo
            {
                get
                {
                    return _agreetermInfo;
                }
            }

            /// <summary>
            /// The TaiKhoản item.
            /// </summary>
            [RepositoryItem("3bc15f56-06f0-44b7-99d4-f278740f1dcc")]
            public virtual Ranorex.ATag TaiKhoản
            {
                get
                {
                    return _taikhoảnInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TaiKhoản item info.
            /// </summary>
            [RepositoryItemInfo("3bc15f56-06f0-44b7-99d4-f278740f1dcc")]
            public virtual RepoItemInfo TaiKhoảnInfo
            {
                get
                {
                    return _taikhoảnInfo;
                }
            }

            /// <summary>
            /// The Thoat item.
            /// </summary>
            [RepositoryItem("312f386b-2021-4064-bddc-4fab7b4d0e7e")]
            public virtual Ranorex.ATag Thoat
            {
                get
                {
                    return _thoatInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Thoat item info.
            /// </summary>
            [RepositoryItemInfo("312f386b-2021-4064-bddc-4fab7b4d0e7e")]
            public virtual RepoItemInfo ThoatInfo
            {
                get
                {
                    return _thoatInfo;
                }
            }

            /// <summary>
            /// The ChucMừngAnhChịĐaĐăngKiThanhCong item.
            /// </summary>
            [RepositoryItem("34feeb44-2cec-4bd7-a54b-4d83b902661e")]
            public virtual Ranorex.PTag ChucMừngAnhChịĐaĐăngKiThanhCong
            {
                get
                {
                    return _chucmừnganhchịđađăngkithanhcongInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ChucMừngAnhChịĐaĐăngKiThanhCong item info.
            /// </summary>
            [RepositoryItemInfo("34feeb44-2cec-4bd7-a54b-4d83b902661e")]
            public virtual RepoItemInfo ChucMừngAnhChịĐaĐăngKiThanhCongInfo
            {
                get
                {
                    return _chucmừnganhchịđađăngkithanhcongInfo;
                }
            }

            /// <summary>
            /// The Skype item.
            /// </summary>
            [RepositoryItem("aa5e61c1-bb2e-488c-aad3-f2d542475b80")]
            public virtual Ranorex.InputTag Skype
            {
                get
                {
                    return _skypeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Skype item info.
            /// </summary>
            [RepositoryItemInfo("aa5e61c1-bb2e-488c-aad3-f2d542475b80")]
            public virtual RepoItemInfo SkypeInfo
            {
                get
                {
                    return _skypeInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("2b331842-31da-4039-a61b-2ed5bb9df1aa")]
            public virtual Ranorex.InputTag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("2b331842-31da-4039-a61b-2ed5bb9df1aa")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The Navbar item.
            /// </summary>
            [RepositoryItem("0a5baa93-1bcc-40ed-afdd-e10568642d47")]
            public virtual Ranorex.DivTag Navbar
            {
                get
                {
                    return _navbarInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Navbar item info.
            /// </summary>
            [RepositoryItemInfo("0a5baa93-1bcc-40ed-afdd-e10568642d47")]
            public virtual RepoItemInfo NavbarInfo
            {
                get
                {
                    return _navbarInfo;
                }
            }

            /// <summary>
            /// The TrangChủ item.
            /// </summary>
            [RepositoryItem("308c9ffb-9fd9-4928-891e-aab654976b5d")]
            public virtual Ranorex.ATag TrangChủ
            {
                get
                {
                    return _trangchủInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TrangChủ item info.
            /// </summary>
            [RepositoryItemInfo("308c9ffb-9fd9-4928-891e-aab654976b5d")]
            public virtual RepoItemInfo TrangChủInfo
            {
                get
                {
                    return _trangchủInfo;
                }
            }

            /// <summary>
            /// The Select2PositionContainer item.
            /// </summary>
            [RepositoryItem("9ca798bd-8358-4e33-b39e-37a14dc24277")]
            public virtual Ranorex.SpanTag Select2PositionContainer
            {
                get
                {
                    return _select2positioncontainerInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Select2PositionContainer item info.
            /// </summary>
            [RepositoryItemInfo("9ca798bd-8358-4e33-b39e-37a14dc24277")]
            public virtual RepoItemInfo Select2PositionContainerInfo
            {
                get
                {
                    return _select2positioncontainerInfo;
                }
            }

            /// <summary>
            /// The ATagTaiKhoản item.
            /// </summary>
            [RepositoryItem("9011d25f-8fc6-433c-9616-15158da9f8e7")]
            public virtual Ranorex.ATag ATagTaiKhoản
            {
                get
                {
                    return _atagtaikhoảnInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagTaiKhoản item info.
            /// </summary>
            [RepositoryItemInfo("9011d25f-8fc6-433c-9616-15158da9f8e7")]
            public virtual RepoItemInfo ATagTaiKhoảnInfo
            {
                get
                {
                    return _atagtaikhoảnInfo;
                }
            }

            /// <summary>
            /// The ColMd9 folder.
            /// </summary>
            [RepositoryFolder("b7601484-9ab3-4aec-b0df-57aefeead214")]
            public virtual ATP_TopCVRepositoryFolders.ColMd9Folder ColMd9
            {
                get { return _colmd9; }
            }

            /// <summary>
            /// The Select2GenderResults folder.
            /// </summary>
            [RepositoryFolder("00211215-fa83-4676-a12f-c4c278bc7b51")]
            public virtual ATP_TopCVRepositoryFolders.Select2GenderResultsFolder Select2GenderResults
            {
                get { return _select2genderresults; }
            }

            /// <summary>
            /// The DivTagRow folder.
            /// </summary>
            [RepositoryFolder("e4c8f385-80ec-441f-89c5-bd2bdb3ecc5d")]
            public virtual ATP_TopCVRepositoryFolders.DivTagRowFolder DivTagRow
            {
                get { return _divtagrow; }
            }
        }

        /// <summary>
        /// The ColMd9Folder folder.
        /// </summary>
        [RepositoryFolder("b7601484-9ab3-4aec-b0df-57aefeead214")]
        public partial class ColMd9Folder : RepoGenBaseFolder
        {
            RepoItemInfo _somebtagInfo;
            RepoItemInfo _spantagnamInfo;
            RepoItemInfo _spantagnữInfo;
            RepoItemInfo _select2selectionarrowInfo;
            RepoItemInfo _spantagchọngiớitinhInfo;
            RepoItemInfo _somespantagInfo;

            /// <summary>
            /// Creates a new ColMd9  folder.
            /// </summary>
            public ColMd9Folder(RepoGenBaseFolder parentFolder) :
                    base("ColMd9", ".//div[#'personal-info']/div[2]/div/div[7]/div", parentFolder, 30000, null, false, "b7601484-9ab3-4aec-b0df-57aefeead214", "")
            {
                _somebtagInfo = new RepoItemInfo(this, "SomeBTag", ".//b", 30000, null, "36fb5d57-cca2-4e57-a446-0d0fa15f7c57");
                _spantagnamInfo = new RepoItemInfo(this, "SpanTagNam", ".//span[@title='Nam']", 30000, null, "9e567331-17dd-4c75-b435-4c821d84da9f");
                _spantagnữInfo = new RepoItemInfo(this, "SpanTagNữ", ".//span[@title='Nữ']", 30000, null, "21af82a9-f1b6-44ea-a274-fac2e3b91fc6");
                _select2selectionarrowInfo = new RepoItemInfo(this, "Select2SelectionArrow", "span/span[1]/span/span[2]", 30000, null, "bf41f7a9-1c0a-4ce2-af45-3eb3571bdcfd");
                _spantagchọngiớitinhInfo = new RepoItemInfo(this, "SpanTagChọnGiớiTinh", ".//span[@title='-- Chọn giới tính --']", 30000, null, "102647fa-247d-4aef-b9bf-420555bc9963");
                _somespantagInfo = new RepoItemInfo(this, "SomeSpanTag", "div[1]//span[@title='Hà Nội']/span[@innertext='×']", 30000, null, "8dc03eb1-6440-413f-b721-75059df62eba");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b7601484-9ab3-4aec-b0df-57aefeead214")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b7601484-9ab3-4aec-b0df-57aefeead214")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeBTag item.
            /// </summary>
            [RepositoryItem("36fb5d57-cca2-4e57-a446-0d0fa15f7c57")]
            public virtual Ranorex.BTag SomeBTag
            {
                get
                {
                    return _somebtagInfo.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The SomeBTag item info.
            /// </summary>
            [RepositoryItemInfo("36fb5d57-cca2-4e57-a446-0d0fa15f7c57")]
            public virtual RepoItemInfo SomeBTagInfo
            {
                get
                {
                    return _somebtagInfo;
                }
            }

            /// <summary>
            /// The SpanTagNam item.
            /// </summary>
            [RepositoryItem("9e567331-17dd-4c75-b435-4c821d84da9f")]
            public virtual Ranorex.SpanTag SpanTagNam
            {
                get
                {
                    return _spantagnamInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagNam item info.
            /// </summary>
            [RepositoryItemInfo("9e567331-17dd-4c75-b435-4c821d84da9f")]
            public virtual RepoItemInfo SpanTagNamInfo
            {
                get
                {
                    return _spantagnamInfo;
                }
            }

            /// <summary>
            /// The SpanTagNữ item.
            /// </summary>
            [RepositoryItem("21af82a9-f1b6-44ea-a274-fac2e3b91fc6")]
            public virtual Ranorex.SpanTag SpanTagNữ
            {
                get
                {
                    return _spantagnữInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagNữ item info.
            /// </summary>
            [RepositoryItemInfo("21af82a9-f1b6-44ea-a274-fac2e3b91fc6")]
            public virtual RepoItemInfo SpanTagNữInfo
            {
                get
                {
                    return _spantagnữInfo;
                }
            }

            /// <summary>
            /// The Select2SelectionArrow item.
            /// </summary>
            [RepositoryItem("bf41f7a9-1c0a-4ce2-af45-3eb3571bdcfd")]
            public virtual Ranorex.SpanTag Select2SelectionArrow
            {
                get
                {
                    return _select2selectionarrowInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Select2SelectionArrow item info.
            /// </summary>
            [RepositoryItemInfo("bf41f7a9-1c0a-4ce2-af45-3eb3571bdcfd")]
            public virtual RepoItemInfo Select2SelectionArrowInfo
            {
                get
                {
                    return _select2selectionarrowInfo;
                }
            }

            /// <summary>
            /// The SpanTagChọnGiớiTinh item.
            /// </summary>
            [RepositoryItem("102647fa-247d-4aef-b9bf-420555bc9963")]
            public virtual Ranorex.SpanTag SpanTagChọnGiớiTinh
            {
                get
                {
                    return _spantagchọngiớitinhInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagChọnGiớiTinh item info.
            /// </summary>
            [RepositoryItemInfo("102647fa-247d-4aef-b9bf-420555bc9963")]
            public virtual RepoItemInfo SpanTagChọnGiớiTinhInfo
            {
                get
                {
                    return _spantagchọngiớitinhInfo;
                }
            }

            /// <summary>
            /// The SomeSpanTag item.
            /// </summary>
            [RepositoryItem("8dc03eb1-6440-413f-b721-75059df62eba")]
            public virtual Ranorex.SpanTag SomeSpanTag
            {
                get
                {
                    return _somespantagInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SomeSpanTag item info.
            /// </summary>
            [RepositoryItemInfo("8dc03eb1-6440-413f-b721-75059df62eba")]
            public virtual RepoItemInfo SomeSpanTagInfo
            {
                get
                {
                    return _somespantagInfo;
                }
            }
        }

        /// <summary>
        /// The Select2GenderResultsFolder folder.
        /// </summary>
        [RepositoryFolder("00211215-fa83-4676-a12f-c4c278bc7b51")]
        public partial class Select2GenderResultsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _litagchọngiớitinhInfo;
            RepoItemInfo _litagnamInfo;
            RepoItemInfo _litagnữInfo;
            RepoItemInfo _nhanvienInfo;
            RepoItemInfo _trưởngnhomInfo;
            RepoItemInfo _phophongInfo;
            RepoItemInfo _trưởngphongInfo;
            RepoItemInfo _phogiamđốcInfo;
            RepoItemInfo _giamđốcInfo;
            RepoItemInfo _tổnggiamđốcInfo;
            RepoItemInfo _litagchọnvịtricongtacInfo;
            RepoItemInfo _litaghanộiInfo;
            RepoItemInfo _noresultsfoundInfo;
            RepoItemInfo _litagbađinhInfo;
            RepoItemInfo _litaghoankiếmInfo;
            RepoItemInfo _litaghaibatrưngInfo;
            RepoItemInfo _litagkinhdoanhbanhangInfo;
            RepoItemInfo _select2resultsoptionsInfo;

            /// <summary>
            /// Creates a new Select2GenderResults  folder.
            /// </summary>
            public Select2GenderResultsFolder(RepoGenBaseFolder parentFolder) :
                    base("Select2GenderResults", "body/span//ul", parentFolder, 30000, null, false, "00211215-fa83-4676-a12f-c4c278bc7b51", "")
            {
                _litagchọngiớitinhInfo = new RepoItemInfo(this, "LiTagChọnGiớiTinh", "li[@innertext='-- Chọn giới tính --']", 30000, null, "681abcf7-c257-4484-b288-eeef776894d3");
                _litagnamInfo = new RepoItemInfo(this, "LiTagNam", "li[@innertext='Nam']", 30000, null, "e1c93eb3-4ae9-45ce-b6eb-023a35e0c41a");
                _litagnữInfo = new RepoItemInfo(this, "LiTagNữ", "li[@innertext='Nữ']", 30000, null, "9b384db1-ebd1-42c8-90e5-a8518f0a7614");
                _nhanvienInfo = new RepoItemInfo(this, "NhanVien", "li[@innertext='Nhân viên']", 30000, null, "2cd72d11-aa97-4ebb-94c3-2c1a66292a25");
                _trưởngnhomInfo = new RepoItemInfo(this, "TrưởngNhom", "li[@innertext='Trưởng nhóm']", 30000, null, "53cb2cd8-7d0a-49aa-9e74-2620a5300254");
                _phophongInfo = new RepoItemInfo(this, "PhoPhong", "li[@innertext='Phó phòng']", 30000, null, "e7950357-7829-4efa-bbcd-c7afaf019c08");
                _trưởngphongInfo = new RepoItemInfo(this, "TrưởngPhong", "li[@innertext='Trưởng phòng']", 30000, null, "e970bd00-e882-43a6-8b3f-0a512f194259");
                _phogiamđốcInfo = new RepoItemInfo(this, "PhoGiamĐốc", "li[@innertext='Phó giám đốc']", 30000, null, "a806ccc4-5d62-4c7a-8a8b-7f6540156c7f");
                _giamđốcInfo = new RepoItemInfo(this, "GiamĐốc", "li[@innertext='Giám đốc']", 30000, null, "de0828bc-8610-4f4b-ae3f-88904550c53f");
                _tổnggiamđốcInfo = new RepoItemInfo(this, "TổngGiamĐốc", "li[@innertext='Tổng giám đốc']", 30000, null, "d20e0f0d-eb88-4920-9059-98b4992dec88");
                _litagchọnvịtricongtacInfo = new RepoItemInfo(this, "LiTagChọnVịTriCongTac", "li[@innertext~'^--\\ Chọn\\ vị\\ trí\\ công\\ tác\\ -']", 30000, null, "d177d073-416b-4294-9192-86b77e144396");
                _litaghanộiInfo = new RepoItemInfo(this, "LiTagHaNội", "li[@innertext='Hà Nội']", 30000, null, "d5bebc65-87da-4a60-b7a0-19f145fe7834");
                _noresultsfoundInfo = new RepoItemInfo(this, "NoResultsFound", "li[@innertext='No results found']", 30000, null, "d55c67c2-1453-4ec3-b710-43786a4b6559");
                _litagbađinhInfo = new RepoItemInfo(this, "LiTagBaĐinh", "li[@innertext='Ba Đình']", 30000, null, "5b099779-41aa-4196-a354-8a8dddd4f073");
                _litaghoankiếmInfo = new RepoItemInfo(this, "LiTagHoanKiếm", "li[@innertext='Hoàn Kiếm']", 30000, null, "0c995811-21f3-43b4-90de-aef68c09a5eb");
                _litaghaibatrưngInfo = new RepoItemInfo(this, "LiTagHaiBaTrưng", "li[@innertext='Hai Bà Trưng']", 30000, null, "f33b9e2f-77ff-4cb8-a395-146c4c8ac821");
                _litagkinhdoanhbanhangInfo = new RepoItemInfo(this, "LiTagKinhDoanhBanHang", "li[@innertext='Kinh doanh / Bán hàng']", 30000, null, "f2ad3d4c-2272-4bea-b332-b6207ab3f062");
                _select2resultsoptionsInfo = new RepoItemInfo(this, "Select2ResultsOptions", "", 30000, null, "3f090a73-3d59-4511-9582-d723e8563f5b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("00211215-fa83-4676-a12f-c4c278bc7b51")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("00211215-fa83-4676-a12f-c4c278bc7b51")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LiTagChọnGiớiTinh item.
            /// </summary>
            [RepositoryItem("681abcf7-c257-4484-b288-eeef776894d3")]
            public virtual Ranorex.LiTag LiTagChọnGiớiTinh
            {
                get
                {
                    return _litagchọngiớitinhInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagChọnGiớiTinh item info.
            /// </summary>
            [RepositoryItemInfo("681abcf7-c257-4484-b288-eeef776894d3")]
            public virtual RepoItemInfo LiTagChọnGiớiTinhInfo
            {
                get
                {
                    return _litagchọngiớitinhInfo;
                }
            }

            /// <summary>
            /// The LiTagNam item.
            /// </summary>
            [RepositoryItem("e1c93eb3-4ae9-45ce-b6eb-023a35e0c41a")]
            public virtual Ranorex.LiTag LiTagNam
            {
                get
                {
                    return _litagnamInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagNam item info.
            /// </summary>
            [RepositoryItemInfo("e1c93eb3-4ae9-45ce-b6eb-023a35e0c41a")]
            public virtual RepoItemInfo LiTagNamInfo
            {
                get
                {
                    return _litagnamInfo;
                }
            }

            /// <summary>
            /// The LiTagNữ item.
            /// </summary>
            [RepositoryItem("9b384db1-ebd1-42c8-90e5-a8518f0a7614")]
            public virtual Ranorex.LiTag LiTagNữ
            {
                get
                {
                    return _litagnữInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagNữ item info.
            /// </summary>
            [RepositoryItemInfo("9b384db1-ebd1-42c8-90e5-a8518f0a7614")]
            public virtual RepoItemInfo LiTagNữInfo
            {
                get
                {
                    return _litagnữInfo;
                }
            }

            /// <summary>
            /// The NhanVien item.
            /// </summary>
            [RepositoryItem("2cd72d11-aa97-4ebb-94c3-2c1a66292a25")]
            public virtual Ranorex.LiTag NhanVien
            {
                get
                {
                    return _nhanvienInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The NhanVien item info.
            /// </summary>
            [RepositoryItemInfo("2cd72d11-aa97-4ebb-94c3-2c1a66292a25")]
            public virtual RepoItemInfo NhanVienInfo
            {
                get
                {
                    return _nhanvienInfo;
                }
            }

            /// <summary>
            /// The TrưởngNhom item.
            /// </summary>
            [RepositoryItem("53cb2cd8-7d0a-49aa-9e74-2620a5300254")]
            public virtual Ranorex.LiTag TrưởngNhom
            {
                get
                {
                    return _trưởngnhomInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The TrưởngNhom item info.
            /// </summary>
            [RepositoryItemInfo("53cb2cd8-7d0a-49aa-9e74-2620a5300254")]
            public virtual RepoItemInfo TrưởngNhomInfo
            {
                get
                {
                    return _trưởngnhomInfo;
                }
            }

            /// <summary>
            /// The PhoPhong item.
            /// </summary>
            [RepositoryItem("e7950357-7829-4efa-bbcd-c7afaf019c08")]
            public virtual Ranorex.LiTag PhoPhong
            {
                get
                {
                    return _phophongInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The PhoPhong item info.
            /// </summary>
            [RepositoryItemInfo("e7950357-7829-4efa-bbcd-c7afaf019c08")]
            public virtual RepoItemInfo PhoPhongInfo
            {
                get
                {
                    return _phophongInfo;
                }
            }

            /// <summary>
            /// The TrưởngPhong item.
            /// </summary>
            [RepositoryItem("e970bd00-e882-43a6-8b3f-0a512f194259")]
            public virtual Ranorex.LiTag TrưởngPhong
            {
                get
                {
                    return _trưởngphongInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The TrưởngPhong item info.
            /// </summary>
            [RepositoryItemInfo("e970bd00-e882-43a6-8b3f-0a512f194259")]
            public virtual RepoItemInfo TrưởngPhongInfo
            {
                get
                {
                    return _trưởngphongInfo;
                }
            }

            /// <summary>
            /// The PhoGiamĐốc item.
            /// </summary>
            [RepositoryItem("a806ccc4-5d62-4c7a-8a8b-7f6540156c7f")]
            public virtual Ranorex.LiTag PhoGiamĐốc
            {
                get
                {
                    return _phogiamđốcInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The PhoGiamĐốc item info.
            /// </summary>
            [RepositoryItemInfo("a806ccc4-5d62-4c7a-8a8b-7f6540156c7f")]
            public virtual RepoItemInfo PhoGiamĐốcInfo
            {
                get
                {
                    return _phogiamđốcInfo;
                }
            }

            /// <summary>
            /// The GiamĐốc item.
            /// </summary>
            [RepositoryItem("de0828bc-8610-4f4b-ae3f-88904550c53f")]
            public virtual Ranorex.LiTag GiamĐốc
            {
                get
                {
                    return _giamđốcInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The GiamĐốc item info.
            /// </summary>
            [RepositoryItemInfo("de0828bc-8610-4f4b-ae3f-88904550c53f")]
            public virtual RepoItemInfo GiamĐốcInfo
            {
                get
                {
                    return _giamđốcInfo;
                }
            }

            /// <summary>
            /// The TổngGiamĐốc item.
            /// </summary>
            [RepositoryItem("d20e0f0d-eb88-4920-9059-98b4992dec88")]
            public virtual Ranorex.LiTag TổngGiamĐốc
            {
                get
                {
                    return _tổnggiamđốcInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The TổngGiamĐốc item info.
            /// </summary>
            [RepositoryItemInfo("d20e0f0d-eb88-4920-9059-98b4992dec88")]
            public virtual RepoItemInfo TổngGiamĐốcInfo
            {
                get
                {
                    return _tổnggiamđốcInfo;
                }
            }

            /// <summary>
            /// The LiTagChọnVịTriCongTac item.
            /// </summary>
            [RepositoryItem("d177d073-416b-4294-9192-86b77e144396")]
            public virtual Ranorex.LiTag LiTagChọnVịTriCongTac
            {
                get
                {
                    return _litagchọnvịtricongtacInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagChọnVịTriCongTac item info.
            /// </summary>
            [RepositoryItemInfo("d177d073-416b-4294-9192-86b77e144396")]
            public virtual RepoItemInfo LiTagChọnVịTriCongTacInfo
            {
                get
                {
                    return _litagchọnvịtricongtacInfo;
                }
            }

            /// <summary>
            /// The LiTagHaNội item.
            /// </summary>
            [RepositoryItem("d5bebc65-87da-4a60-b7a0-19f145fe7834")]
            public virtual Ranorex.LiTag LiTagHaNội
            {
                get
                {
                    return _litaghanộiInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagHaNội item info.
            /// </summary>
            [RepositoryItemInfo("d5bebc65-87da-4a60-b7a0-19f145fe7834")]
            public virtual RepoItemInfo LiTagHaNộiInfo
            {
                get
                {
                    return _litaghanộiInfo;
                }
            }

            /// <summary>
            /// The NoResultsFound item.
            /// </summary>
            [RepositoryItem("d55c67c2-1453-4ec3-b710-43786a4b6559")]
            public virtual Ranorex.LiTag NoResultsFound
            {
                get
                {
                    return _noresultsfoundInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The NoResultsFound item info.
            /// </summary>
            [RepositoryItemInfo("d55c67c2-1453-4ec3-b710-43786a4b6559")]
            public virtual RepoItemInfo NoResultsFoundInfo
            {
                get
                {
                    return _noresultsfoundInfo;
                }
            }

            /// <summary>
            /// The LiTagBaĐinh item.
            /// </summary>
            [RepositoryItem("5b099779-41aa-4196-a354-8a8dddd4f073")]
            public virtual Ranorex.LiTag LiTagBaĐinh
            {
                get
                {
                    return _litagbađinhInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagBaĐinh item info.
            /// </summary>
            [RepositoryItemInfo("5b099779-41aa-4196-a354-8a8dddd4f073")]
            public virtual RepoItemInfo LiTagBaĐinhInfo
            {
                get
                {
                    return _litagbađinhInfo;
                }
            }

            /// <summary>
            /// The LiTagHoanKiếm item.
            /// </summary>
            [RepositoryItem("0c995811-21f3-43b4-90de-aef68c09a5eb")]
            public virtual Ranorex.LiTag LiTagHoanKiếm
            {
                get
                {
                    return _litaghoankiếmInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagHoanKiếm item info.
            /// </summary>
            [RepositoryItemInfo("0c995811-21f3-43b4-90de-aef68c09a5eb")]
            public virtual RepoItemInfo LiTagHoanKiếmInfo
            {
                get
                {
                    return _litaghoankiếmInfo;
                }
            }

            /// <summary>
            /// The LiTagHaiBaTrưng item.
            /// </summary>
            [RepositoryItem("f33b9e2f-77ff-4cb8-a395-146c4c8ac821")]
            public virtual Ranorex.LiTag LiTagHaiBaTrưng
            {
                get
                {
                    return _litaghaibatrưngInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagHaiBaTrưng item info.
            /// </summary>
            [RepositoryItemInfo("f33b9e2f-77ff-4cb8-a395-146c4c8ac821")]
            public virtual RepoItemInfo LiTagHaiBaTrưngInfo
            {
                get
                {
                    return _litaghaibatrưngInfo;
                }
            }

            /// <summary>
            /// The LiTagKinhDoanhBanHang item.
            /// </summary>
            [RepositoryItem("f2ad3d4c-2272-4bea-b332-b6207ab3f062")]
            public virtual Ranorex.LiTag LiTagKinhDoanhBanHang
            {
                get
                {
                    return _litagkinhdoanhbanhangInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagKinhDoanhBanHang item info.
            /// </summary>
            [RepositoryItemInfo("f2ad3d4c-2272-4bea-b332-b6207ab3f062")]
            public virtual RepoItemInfo LiTagKinhDoanhBanHangInfo
            {
                get
                {
                    return _litagkinhdoanhbanhangInfo;
                }
            }

            /// <summary>
            /// The Select2ResultsOptions item.
            /// </summary>
            [RepositoryItem("3f090a73-3d59-4511-9582-d723e8563f5b")]
            public virtual Ranorex.UlTag Select2ResultsOptions
            {
                get
                {
                    return _select2resultsoptionsInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Select2ResultsOptions item info.
            /// </summary>
            [RepositoryItemInfo("3f090a73-3d59-4511-9582-d723e8563f5b")]
            public virtual RepoItemInfo Select2ResultsOptionsInfo
            {
                get
                {
                    return _select2resultsoptionsInfo;
                }
            }
        }

        /// <summary>
        /// The DivTagRowFolder folder.
        /// </summary>
        [RepositoryFolder("e4c8f385-80ec-441f-89c5-bd2bdb3ecc5d")]
        public partial class DivTagRowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _select2selectionarrow1Info;
            RepoItemInfo _somebtag1Info;
            RepoItemInfo _select2selectionarrow2Info;

            /// <summary>
            /// Creates a new DivTagRow  folder.
            /// </summary>
            public DivTagRowFolder(RepoGenBaseFolder parentFolder) :
                    base("DivTagRow", ".//div[#'personal-info']/div[2]/div/div[10]/div/div", parentFolder, 30000, null, false, "e4c8f385-80ec-441f-89c5-bd2bdb3ecc5d", "")
            {
                _select2selectionarrow1Info = new RepoItemInfo(this, "Select2SelectionArrow1", "div[1]/div/span/span[1]/span/span[2]", 30000, null, "195ffb00-0a91-49ad-aa28-f9fb00ab02dc");
                _somebtag1Info = new RepoItemInfo(this, "SomeBTag1", "div[2]/div/span//b", 30000, null, "2164d584-b99e-4acb-b193-1bc67c43686e");
                _select2selectionarrow2Info = new RepoItemInfo(this, "Select2SelectionArrow2", "div[2]/div/span/span[1]/span/span[2]", 30000, null, "3681b5a5-1729-439f-ad6f-333a2fdba28e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e4c8f385-80ec-441f-89c5-bd2bdb3ecc5d")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e4c8f385-80ec-441f-89c5-bd2bdb3ecc5d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Select2SelectionArrow1 item.
            /// </summary>
            [RepositoryItem("195ffb00-0a91-49ad-aa28-f9fb00ab02dc")]
            public virtual Ranorex.SpanTag Select2SelectionArrow1
            {
                get
                {
                    return _select2selectionarrow1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Select2SelectionArrow1 item info.
            /// </summary>
            [RepositoryItemInfo("195ffb00-0a91-49ad-aa28-f9fb00ab02dc")]
            public virtual RepoItemInfo Select2SelectionArrow1Info
            {
                get
                {
                    return _select2selectionarrow1Info;
                }
            }

            /// <summary>
            /// The SomeBTag1 item.
            /// </summary>
            [RepositoryItem("2164d584-b99e-4acb-b193-1bc67c43686e")]
            public virtual Ranorex.BTag SomeBTag1
            {
                get
                {
                    return _somebtag1Info.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The SomeBTag1 item info.
            /// </summary>
            [RepositoryItemInfo("2164d584-b99e-4acb-b193-1bc67c43686e")]
            public virtual RepoItemInfo SomeBTag1Info
            {
                get
                {
                    return _somebtag1Info;
                }
            }

            /// <summary>
            /// The Select2SelectionArrow2 item.
            /// </summary>
            [RepositoryItem("3681b5a5-1729-439f-ad6f-333a2fdba28e")]
            public virtual Ranorex.SpanTag Select2SelectionArrow2
            {
                get
                {
                    return _select2selectionarrow2Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Select2SelectionArrow2 item info.
            /// </summary>
            [RepositoryItemInfo("3681b5a5-1729-439f-ad6f-333a2fdba28e")]
            public virtual RepoItemInfo Select2SelectionArrow2Info
            {
                get
                {
                    return _select2selectionarrow2Info;
                }
            }
        }

        /// <summary>
        /// The SavePasswordAppFolder folder.
        /// </summary>
        [RepositoryFolder("efecb01f-bac5-4b91-9197-6e9479053fc2")]
        public partial class SavePasswordAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pushbuttonInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new SavePassword  folder.
            /// </summary>
            public SavePasswordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SavePassword", "/form[@title='Save password?']", parentFolder, 30000, null, true, "efecb01f-bac5-4b91-9197-6e9479053fc2", "")
            {
                _pushbuttonInfo = new RepoItemInfo(this, "PushButton", "element[@accessiblename='Save password?']//button[@accessiblename='']", 30000, null, "74500ebf-a0c3-4d0d-b52e-99921a5ca842");
                _closeInfo = new RepoItemInfo(this, "Close", "container/container[1]/button[@accessiblename='Close']", 30000, null, "056804a9-1b82-4b2f-b190-d104354b0f82");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("efecb01f-bac5-4b91-9197-6e9479053fc2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("efecb01f-bac5-4b91-9197-6e9479053fc2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PushButton item.
            /// </summary>
            [RepositoryItem("74500ebf-a0c3-4d0d-b52e-99921a5ca842")]
            public virtual Ranorex.Button PushButton
            {
                get
                {
                    return _pushbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PushButton item info.
            /// </summary>
            [RepositoryItemInfo("74500ebf-a0c3-4d0d-b52e-99921a5ca842")]
            public virtual RepoItemInfo PushButtonInfo
            {
                get
                {
                    return _pushbuttonInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("056804a9-1b82-4b2f-b190-d104354b0f82")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("056804a9-1b82-4b2f-b190-d104354b0f82")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("3693d967-bd3a-49ff-b378-91e2289a9c90")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "3693d967-bd3a-49ff-b378-91e2289a9c90", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3693d967-bd3a-49ff-b378-91e2289a9c90")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3693d967-bd3a-49ff-b378-91e2289a9c90")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
