///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATP_TopCV
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Check_hien_thi_gia_tri_Quan_huyen recording.
    /// </summary>
    [TestModule("79356054-8a76-4152-b8da-c5f527a2e21b", ModuleType.Recording, 1)]
    public partial class Check_hien_thi_gia_tri_Quan_huyen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATP_TopCVRepository repository.
        /// </summary>
        public static ATP_TopCVRepository repo = ATP_TopCVRepository.Instance;

        static Check_hien_thi_gia_tri_Quan_huyen instance = new Check_hien_thi_gia_tri_Quan_huyen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Check_hien_thi_gia_tri_Quan_huyen()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Check_hien_thi_gia_tri_Quan_huyen Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2' at 7;21.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2Info, new RecordItemIndex(0));
            repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2.Click("7;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'No results found') on item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.NoResultsFound'.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.NoResultsFoundInfo, new RecordItemIndex(1));
            Validate.AttributeContains(repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.NoResultsFoundInfo, "InnerText", "No results found");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow1' at 18;20.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow1Info, new RecordItemIndex(2));
            repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow1.Click("18;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagHaNội' at 80;12.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagHaNộiInfo, new RecordItemIndex(3));
            repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagHaNội.Click("80;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2' at 8;30.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2Info, new RecordItemIndex(4));
            repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2.Click("8;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\nBa Đình\n') on item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagBaĐinh'.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagBaĐinhInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagBaĐinhInfo, "InnerText", "\nBa Đình\n");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\nHoàn Kiếm\n') on item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagHoanKiếm'.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagHoanKiếmInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagHoanKiếmInfo, "InnerText", "\nHoàn Kiếm\n");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\nHai Bà Trưng\n') on item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagHaiBaTrưng'.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagHaiBaTrưngInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagHaiBaTrưngInfo, "InnerText", "\nHai Bà Trưng\n");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagBaĐinh' at 73;20.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagBaĐinhInfo, new RecordItemIndex(8));
            repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagBaĐinh.Click("73;20");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\nBa Đình\n') on item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2'.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2Info, new RecordItemIndex(9));
            //Validate.AttributeEqual(repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2Info, "InnerText", "\nBa Đình\n");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\nBa Đình\n') on item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow1'.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow1Info, new RecordItemIndex(10));
            //Validate.AttributeEqual(repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow1Info, "InnerText", "\nBa Đình\n");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SomeSpanTag' at 4;19.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SomeSpanTagInfo, new RecordItemIndex(11));
            //repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SomeSpanTag.Click("4;19");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2' at 5;20.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2Info, new RecordItemIndex(12));
            //repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.DivTagRow.Select2SelectionArrow2.Click("5;20");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'No results found') on item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.NoResultsFound'.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.NoResultsFoundInfo, new RecordItemIndex(13));
            //Validate.AttributeContains(repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.NoResultsFoundInfo, "InnerText", "No results found");
            //Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
