///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATP_TopCV
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Test_chon_gia_tri_gioi_tinh recording.
    /// </summary>
    [TestModule("f3b97046-bfd1-4e0a-b3fb-a1d8e626f31d", ModuleType.Recording, 1)]
    public partial class Test_chon_gia_tri_gioi_tinh : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATP_TopCVRepository repository.
        /// </summary>
        public static ATP_TopCVRepository repo = ATP_TopCVRepository.Instance;

        static Test_chon_gia_tri_gioi_tinh instance = new Test_chon_gia_tri_gioi_tinh();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Test_chon_gia_tri_gioi_tinh()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Test_chon_gia_tri_gioi_tinh Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SomeBTag' at 2;4.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SomeBTagInfo, new RecordItemIndex(0));
            repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SomeBTag.Click("2;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagNam' at 200;30.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagNamInfo, new RecordItemIndex(1));
            repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagNam.Click("200;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'Nam') on item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SpanTagNam'.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SpanTagNamInfo, new RecordItemIndex(2));
            Validate.AttributeContains(repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SpanTagNamInfo, "InnerText", "Nam");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SomeBTag' at 3;1.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SomeBTagInfo, new RecordItemIndex(3));
            repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SomeBTag.Click("3;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagNữ' at 274;8.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagNữInfo, new RecordItemIndex(4));
            repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagNữ.Click("274;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'Nữ') on item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SpanTagNữ'.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SpanTagNữInfo, new RecordItemIndex(5));
            Validate.AttributeContains(repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SpanTagNữInfo, "InnerText", "Nữ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.Select2SelectionArrow' at 12;15.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.Select2SelectionArrowInfo, new RecordItemIndex(6));
            repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.Select2SelectionArrow.Click("12;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagChọnGiớiTinh' at 161;4.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagChọnGiớiTinhInfo, new RecordItemIndex(7));
            repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.Select2GenderResults.LiTagChọnGiớiTinh.Click("161;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'-- Chọn giới tính --') on item 'ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SpanTagChọnGiớiTinh'.", repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SpanTagChọnGiớiTinhInfo, new RecordItemIndex(8));
            Validate.AttributeContains(repo.ĐăngKyTaiKhoảnNhaTuyểnDụng.ColMd9.SpanTagChọnGiớiTinhInfo, "InnerText", "-- Chọn giới tính --");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
